luca652/volo

app/controllers/groups_controller.rb, app/controllers/requests_controller.rb, app/views/groups/index.html.erb, config/routes.rb
I added index action to controller
=> Created groups controller

Gemfile.lock, app/assets/stylesheets/resources.css, app/controllers/resources_controller.rb, app/javascript/resources.js, app/views/resources/index.html.erb, config/application.rb, config/routes.rb, db/schema.rb, db/seeds.rb
cards appearing beneath each other, some random seeds added to console
=> Resources page draft 1 16:45 on 3rd June 2023

Gemfile, Gemfile.lock, app/assets/stylesheets/resources.css, app/controllers/resources_controller.rb, app/javascript/controllers/application.js, app/javascript/resources.js, app/views/resources/index.html.erb, package.json, yarn.lock
filter feature added on the resources page
=> My-filter 

app/views/layouts/application.html.erb, app/views/pins/index.html.erb, config/routes.rb
i have added the delete button on the pinned card on the /pins page
=> delete button added

app/controllers/pins_controller.rb, app/models/pin.rb, app/models/user.rb, app/views/resources/index.html.erb
pin-once feature, no more duplicate pins in the pins page
=> ability to pin a card only once

app/views/resources/index.html.erb
the user has the ability to create a resource card
=> create resource done

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_group_footer.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_colors.scss, app/assets/stylesheets/pages/_group_show.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/groups_controller.rb, app/javascript/controllers/footer_controller.js, app/javascript/controllers/index.js, app/views/groups/show.html.erb, app/views/layouts/application.html.erb, app/views/shared/_group_footer.html.erb, db/seeds.rb
The group show page is now fully styled. 
I still have a problem styling the footer, at the moment the footer is transparent but I think it is better to have it on a grey background.
=> create group show page

app/views/groups/show.html.erb, db/seeds.rb
I added a link to google maps on event cards.
I also formatted the date so that it shows the time of the event.
=> Event cards

Gemfile.lock, app/controllers/resources_controller.rb, app/javascript/application.js, app/models/resource.rb, app/views/resources/index.html.erb, yarn.lock
[Pins documentation.docx](https://github.com/luca652/volo/files/11712236/Pins.documentation.docx)
attached documentation on how it works logically. 
If another user logs in then also the pin count is incremented, a user can only increment by 1 .
=> pins count made

app/controllers/pins_controller.rb, app/views/resources/index.html.erb
asynchronous pinning added! No need to refresh
=> async pins

app/assets/stylesheets/components/_group_footer.scss, app/assets/stylesheets/components/_index.scss
I have fixed the layout of the footer in the group-show page
=> fixed layout

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_group_show.scss, app/javascript/controllers/dropdown_controller.js, app/views/groups/show.html.erb, package.json, yarn.lock
I have added a dropdown effect on the events div.
=> Events dropdown

app/controllers/groups_controller.rb, app/javascript/controllers/chatroom_subscription_controller.js, app/views/chatrooms/show.html.erb, app/views/groups/_info_window.html.erb, app/views/groups/index.html.erb, db/migrate/20230615110615_remove_childrens_age_from_groups.rb, db/migrate/20230615110726_add_childre_age_to_groups.rb, db/schema.rb, db/seeds.rb
After merging this branch, please run db:migrate and db:seed.
I modified the schema, now the children_age is a string. This allowed me to create a filter function on the group's index page. The descriptions of the groups now carry more information about the events they organise, and it is displayed on the cards.
I have also added other groups on the map so we can use the search bar on the map.
=> Filter seeds

app/assets/stylesheets/components/_chatroom.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_message.scss, app/controllers/messages_controller.rb, app/javascript/controllers/chatroom_subscription_controller.js, app/javascript/controllers/footer_controller.js, app/models/message.rb, app/views/chatrooms/show.html.erb, app/views/shared/_navbar.html.erb
=> Chatroom styling

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_group_footer.scss, app/views/shared/_footer.html.erb, app/views/shared/_group_footer.html.erb
I have added the stories link to both the footers
=> Add stories to footers

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show_story.scss, app/views/stories/show_story.html.erb, db/seeds.rb
=> Resources images problem

app/assets/stylesheets/components/_avatar.scss, app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> resized navbar

app/assets/stylesheets/resources.css, app/views/resources/index.html.erb
resources paged styled as per mypins page
=> styledResources

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/pages/_show_profile.scss, app/views/shared/_footer.html.erb, app/views/stories/index.html.erb, app/views/users/show_profile.html.erb
Restyled footer and added magic wand icon
=> Edit button

app/assets/stylesheets/pages/_show_profile.scss, app/assets/stylesheets/pages/_show_story.scss, app/views/users/show_profile.html.erb
I have modified Laura profile, to highlight info like no of children, age and interest.
=> Laura profile

config/routes.rb
removed route to home page 
logging in redirects to groups index
=> removed route to home page

app/assets/stylesheets/pages/_groups_index.scss, app/assets/stylesheets/pages/_resources.scss, app/assets/stylesheets/pages/_show_profile.scss, app/views/resources/index.html.erb, app/views/users/show_profile.html.erb, db/seeds.rb
Small style changes in accordance with feedback
=> Very last bits

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/mixins/_media.scss, app/controllers/groups_controller.rb
- Styled age filter
- Made it responsive so that on screens for tablets and up it displays on the top right and on mobile on the bottom right above footer
=> Search and filter index page

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_event.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_group_footer.scss, app/assets/stylesheets/config/_basics.scss, app/assets/stylesheets/pages/_group_show.scss, app/assets/stylesheets/pages/_info_window.scss, app/assets/stylesheets/pages/_resource_show.scss, app/assets/stylesheets/pages/_resources.scss, app/assets/stylesheets/pages/_show_profile.scss, app/controllers/groups_controller.rb, app/views/groups/edit.html.erb, app/views/groups/show.html.erb, config/routes.rb
Users can now update or delete a group that they have created.
=> Update and destroy group

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_resource.scss, app/assets/stylesheets/config/_basics.scss, app/assets/stylesheets/pages/_group_show.scss, app/assets/stylesheets/pages/_resources.scss, app/assets/stylesheets/pages/_show_profile.scss, app/views/groups/_group.html.erb, app/views/resources/_resource.html.erb, app/views/resources/index.html.erb, app/views/resources/show.html.erb
Created a resource show pages, put a link to the show page on every card. if current_user created the resource, the edit and delete buttons are rendered on the show page.
=> Resource show page

app/assets/stylesheets/components/_map.scss, app/controllers/bookings_controller.rb, app/controllers/events_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/views/events/_event.html.erb, app/views/events/create.html.erb, app/views/events/destroy.html.erb, app/views/events/edit.html.erb, app/views/events/index.html.erb, app/views/events/new.html.erb, app/views/events/show.html.erb, app/views/events/update.html.erb, config/routes.rb, test/controllers/events_controller_test.rb
- Fixed issues with path to destroy booking on event partial
=> Fix bookings bug

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_separators.scss, app/assets/stylesheets/pages/_group_show.scss, app/assets/stylesheets/pages/_show_profile.scss, app/assets/stylesheets/pages/_stories_index.scss, app/controllers/bookings_controller.rb, app/controllers/stories_controller.rb, app/controllers/users_controller.rb, app/views/events/_event.html.erb, app/views/groups/show.html.erb, app/views/stories/new.html.erb, app/views/users/show_profile.html.erb, config/routes.rb, db/seeds.rb
Fixed style of groups show page and made it responsive
=> Group show responsive

Gemfile, Gemfile.lock, app/controllers/groups_controller.rb, app/javascript/controllers/index.js, app/models/group.rb
When a user creates a group, a new chatroom for the group is automatically created.
=> New chatroom when new group

Gemfile.lock, app/assets/stylesheets/pages/_resources.scss, app/controllers/groups_controller.rb, app/controllers/resources_controller.rb, app/views/resources/index.html.erb
- Created a filter on resources index page. Resources can now be filtered by category
=> Fix resources filter

app/controllers/prompts_controller.rb, app/controllers/stories_controller.rb, app/views/stories/new.html.erb, config/routes.rb
Moved the creation of prompts to the prompts controller from the stories controller
=> Prompts controller

app/controllers/users_controller.rb, app/models/prompt.rb, db/schema.rb, db/seeds.rb
- Fixed issue with event in seeds (event must be in the future)
- Added validations to prompts
=> Demo fixes

app/javascript/controllers/oval_controller.js, app/views/stories/new.html.erb, spec/models/prompt_spec.rb, spec/models/story_spec.rb, spec/models/user_spec.rb
Add model tests for:
- User
- Event
- Group
- Prompt
- Story
=> Model tests

app/controllers/stories_controller.rb, app/models/story.rb, spec/models/story_spec.rb, spec/services/story_generator_spec.rb
- Add validations for presence to the title and content attributes of the story model
- Add rescue in controller to handle validations error gracefully
- Add model tests for Story model
- Add tests for #extrac_title_and_story and #generate_story
=> Add validations to Story model

app/models/prompt.rb, app/models/user.rb
- Add has_many prompts to user model
- remove minimum lenght from length validations
=> Models and validations
